name: Deploy To Render

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  ci:
    name: Run Tests and Deploy (if main)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      # Run tests (Vitest, Jest, etc.)
      - name: Run Unit Tests
        run: npm run test

      # Only deploy if on main
      - name: Deploy to Render (only for main)
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_MAIN_DEPLOY_HOOK_URL }}
        run: |
          echo "Triggering deployment on Render..."
          curl "$deploy_url"

      # Only wait for deployment if on main
      - name: Wait for Render Deployment (only for main)
        if: github.ref == 'refs/heads/main'
        run: npx wait-on https://ci-cd-pipelines.onrender.com --timeout 120000

      # Only run Cypress tests against the deployed app if on main
      - name: Run Cypress Tests (only for main)
        if: github.ref == 'refs/heads/main'
        run: npx cypress run --config baseUrl=https:/
