name: Deploy To Render

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  ci:
    name: Run Tests and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      # Start the app in the background and log output
      - name: Start Application
        run: npm start > server-log.txt 2>&1 &

      # Debug: Check if the app is actually running
      - name: Debug Running Processes
        run: ps aux

      # Debug: Check server logs for errors
      - name: Print Server Logs
        run: cat server-log.txt

      # Wait until the server is ready before running Cypress tests
      - name: Wait for Server to Start
        run: npx wait-on http://localhost:3001 --timeout 60000  # Increase timeout if needed

      - name: Run Cypress Tests
        run: npx cypress run --config baseUrl=http://localhost:3001 --config pageLoadTimeout=30000

      # Deploy to Render based on branch
      - name: Deploy to Render
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEV_DEPLOY_HOOK_URL }}
        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
            echo "Deploying to main environment..."
            curl "${{ secrets.RENDER_MAIN_DEPLOY_HOOK_URL }}"
          else
            echo "Deploying to dev environment..."
            curl "${{ secrets.RENDER_DEV_DEPLOY_HOOK_URL }}"
          fi
