name: Deploy To Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install
      - name: Start Server
        run: |
          npm start &
      - name: Wait for Server
        run: |
          sleep 30
      - name: Check Server
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3001; do
            printf '.'
            sleep 5
          done
      - name: Test
        run: |
          npm run test
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"